const fortune = [

    "Today you are the great harmonizer and home-maker. You would like to make everybody comfortable and happy. You are a nurse, teacher, father (or mother), confessor, counselor, host or companion - all in one.If you see an urgent need for physical drudgery and you seem to be the one elected to do it, you are not going to keep your mind on the soap and scrub brush, but on the shining result to be achieved. You are going to keep busy and even-tempered, but refrain from bustling about or allowing anyone to see the wheels in operation. You are going to finish anything you undertake.You are full of high principles and a great desire to adjust other lives as harmoniously as you have managed your own, but you realize the danger of becoming a chatterer and a busybody, and wisely decide to wait until your sympathy and advice are asked for. Your sense of duty and responsibility are at their keenest, and you realize that today is the time to work them, for if any of the demands are neglected, you know they will rise and smite you at a time when you would seem an impossible burden.Today it is easy.You are headed for a well-earned rest - tomorrow.\n",

    "After the spiritual housecleaning of yesterday, you are ready to turn your attention to purely material affairs.You realize that there is an atmosphere of worldly power and financial gain about you.Your success is in your hands, provided you do not confuse ends and means.You are not dependent upon others but stand upon your own feet and attract their confidence by your strength. You know that money, in itself, is only a stepping-stone, and you have the clear sense and judgment to want to accumulate it for the power-for-good its possession will bring you.You want to help others as well as yourself, partly because you want to live on the constructive side and partly because have the intelligence to know that, of all the existing vibrations, it is the most elusive when you think only for yourself.\n",

    " Being the most practical, you do not expect of it much inspiration or uplift, but you can endow it with those qualities that you draw from your store, and in that way increase its power of attraction toward you.You know, too, that if you have a thing within your grasp and allow yourself to become hard and domineering, it cannot and will not remain with you, but will inevitably turn against you and refuse to lend a hand in your affairs.You feel the power and construction, multiplied by the kindness and beneficence.",

    "Since this day is a day of high spiritual vibration, it is not always friendly to strictly material affairs.You will have a feeling of withdrawal from the world that you will have a good sense not to carry too far.If you want to be along and can manage it, you must not spoil it all by feeling melancholy. If you are out of sympathy with what seems to be meaningless activity about you, you won't allow it to irritate or depress you, make your restless and dissatisfied or critical and intolerant.You know that you are fully capable of any effort required of you, whether you feel inclined to it or not, for your internal force and balance see you through. You know that if you keep still and wait, things will come to you if you go out after them, they will elude or disappoint you. You may be conscious of a thousand irritations, like an army of small devils, trying to throw you off your balance, but since you realize that this is a day that belongs to your inner life, you know they cannot penetrate deep enough to reach it, so you will only laugh at their antics. You are acquiring an excellent reserve-force for tomorrow.\n",

    "  Today you are in the vibration of Universal Love. You belong to the world at large and see everything in broad sweeps.You realize that you can do nothing for yourself alone for it will boomerang back to you.Today you cannot allow yourself to become impatient with opposition or despise another's point of view, because you realize that you were once, a concise time ago, as unenlightened as those others who are looking through the wrong end of the telescope.\n",

    " You are so thrilled with the new outlook that you want to give everyone a hand-up and let all share it. You realize that tomorrow will start a new cycle of achievement and are, therefore, determined to leave no loose ends to be carried over.If you do, they will drag along interminably.You are closing a chapter and are wise enough to do it effectively and thoroughly.Mistakes and ugliness are all beneath and behind you.\n",

    "   Today your personal power and individuality are at their height.You are independent, ambitious, energetic and self-reliant.Your intellect is working under full steam. Your judgment is excellent.ou have the courage and determination to carry out your plans for a successful conclusion.You have a good sense to realize that impatience, anger, stubbornness, arrogance, selfishness, laziness, worry, anxiety and unwillingness to unite yourself with any conditions that arise would only cause you to lose control of a situation that is entirely in your hands.Your strong-willed attitude will carry you where you want to go.",

    "    Today may mean for you a big step forward, or it may throw you. It will depend on how you handle things. It is not easy, because it has nothing to do with practical affairs.Today you are offered a bridge to Gods - shown to you so you can show it to others! It is the Light of the World - for the World. This day brings no personal rewards except through service and healing.It demands the expression of your best. It \"shows you up\" as you are. Today you are open to the mastery of life.\n",

    " you love the world and understand why so much has been said and written about \"Joy of living.\" If anything hits you, you can't stay down.You don't care especially about working with your hands today, for the artist in you is on top and clamoring to be recognized.You can sing, dance, play, act, speak or write.",

    " You are stalwart, dependable, full of useful purpose. You are laying the foundation for your building, so you want to be sure of the size and quality.You recognize the beauty of perfect construction, knowing that it holds the promise of definite and enduring completion.You know that a good foundation means protection, and stability is necessary to make freedom.You are wise enough to realize that all your work doesn't mean monotony, that perfectionists are not always the best critics and that the most painstaking people need not be unduly slow.\n",

    "   you are not a specialist, rather the best salesman you can turn your hand to anything you like.Your mind is especially keen, and you have on the top of your tongue that bit of brilliant repartee you wanted yesterday. You are a gypsy and along for the trail failing that, you are free to seek as much mental adventure as you please.The importance of affairs is in the background, and you are ready to play.You are going to take that short trip that seemed inadvisable yesterday (it probably was), for you know that today the conditions are excellent for it, and you will have the outcome you are looking for.It is a good day to invite friends, especially those who have begun to feel neglected. No one can prevent you from making an adventure out of today. Your \"luck\" is with you and you mean to make the most of it. You have a tremendous amount of vitality and energy, but you know better than to waste any of it in losing your temper or get nervous. You also have a good sense to realize that the kind of freedom you are after isn't to be found in the bottom of a glass, in putting your money on any old horse that is posted, or in taking your friend's best girl to dinner.You are out for something to keep. You will know more tomorrow than you did yesterday.\n",

    "  You are laying the foundation for your building, so you want to be sure of the size and quality. You recognize the beauty of perfect construction, knowing that it holds the promise of definite and enduring completion.You know that a good foundation means protection, and stability is necessary to make freedom.You are wise enough to realize that all your work doesn't mean monotony, that perfectionists are not always the best critics and that the most painstaking people need not be unduly slow.\n",

    " your personal power and individuality are at their height.You are independent, ambitious, energetic and self-reliant.Your intellect is working under full steam. Your judgment is excellent.You have the courage and determination to carry out your plans for a successful conclusion.You have a good sense to realize that impatience, anger, stubbornness, arrogance, selfishness, laziness, worry, anxiety and unwillingness to unite yourself with any conditions that arise would only cause you to lose control of a situation that is entirely in your hands.Your strong-willed attitude will carry you where you want to go\n",

    "    You are not always consistent in your temperament, experiencing great highs and lows; you are sometimes docile, sometimes in a black temper.However, this variance of mood always implies a chameleon-like intellect that can match the mood of times, advancing or remaining static as the situation demands.\n",

    "You thoroughly enjoy everything that goes on in this great universe.Your interest, combined with your wit and sense of humor, makes you the center of attraction of any group.Words are gems you enjoy giving to those around you, and means by which you express all you have learned and experienced.Though usually humorous,you are by no means merely a clown.Serious subjects are also your pleasure, and you express yourself well, but take care to show your knowledge is complete.You can easily misinform people because your way of expressing orally can hold them capative,and they often believe whatever you say.\n",

    "You are very sexual in thought and action, and this results in a magnetic quality that draws people to you.Should you venture onto the subjects you know too little about, you may well find yourself in an extremely embarrassing position.Once made to look foolish, you will be hard pressed to vindicate yourself and you will not command the sttention you are fond of.\n",

    "Yours is the role of philosopher, teacher, and healer, but it will not be easy for you to teach unless yu can loosen up a bit in your outward personality.Your reserved nature gives the impression of being unapproachable.Only those who understand these quiet, contemplative moods can get through to you.These are the fortunate ones because you have so mmuch to give.\n",

    "Your interests are mainly cultural, mental, and philosophical.The finer things in life are as necessary to you as the air you breathe.All things beautiful impress you: a well-done painting, a beautiful sculpture, or a good book.You could not live without these things to enjoy.You are the rare individual who can enjoy every stroke of the brush in a painting, not just the overall effect.You would make an excellent parent because you could teach a child the appreciation of all the beauty life has to offer, both in an intellectual and physical sense.\n",

    "Your Strong sense of individuality and positive nature assure you of leadership in all your endeavors.You can never be relegated to a position of subservience. Determination is the strength of your ambition, and it manifests itself in an authoritative manner that shows your skill and experience. Your originality, creativeness, and aggressiveness breathe life into your ideas and build them into productive form. You are blessed with executive ability and can manage the organization of any business, group, or household with great ease and success.\n",

    " You are at your best when you start any project from its conception and learn by your mistakes.Stand on your own feet no matter how difficult a situation may be,whether in business or of a personal nature.Always make your own decisions and stand by them in spite of advisers who are not in agreement.Extend yourself in all fields of interest because success is yours,no matter what area you choose.\n",

    " You will never walk the common paths, but search out new, more exciting ones, which will generally prove fruitful.There is no need to repeat yourself.You can take the lead in anything and, therefore,new ideas are necessary.\n",

    "your extreme sensitivity makes you understand respond easily to people, atmosphere, attitudes, music, sounds, color, and personalities.This makes you every perceptive and actuates your interest in the meaning behind everything you come across, especially the so-called dark sciences, such as the occult.All things mystic appeal to you, and you feel the need to delve into these things too see for yourself just what they may hold for you.You are also quite psychic and a perfect candidate for ESP and all related subjects.\n",

    "Love is so important to you that you can love more than one person at a time, or group of people, thereby experiencing the great joy of this love in so many different areas.It wouls wrong for you to pursue only one great romance in your entire life.Give in the wonderful ecstasies and sadness, take from them what you have learned and apply them to the next.Only then can you find complete contentment in a total relationship.\n",

    "Your concern for and interest in others tends to unnerve you at times, causing you to either rise to the heights of ecstasy or sink into the depths of depression.Once you learn to control your emotions intelligently through the study of philosophy, metaphysics, and other spiritual interests, you will risk like phoenix from the ashes and take your place in the world as truly enlightened person.No longer will you experience depression or terrible sadness over the way people walk all over you.You will understand the reason for everythings that happens to you and anxiously await the next installement, knowing that all things happen for the best.You will look eagerly for the lessons to be taught and always find them, to your great joy and happiness.Your marvelous generosity will manifest itself in the extension of these thruths to all you can make understand them, in an effort to help all mankind.Feel the contentmnt and peace that you have been privileged to experience.\n",

    "You are the ideal mate, friend, or employee. For this reason it is best to always follow the well-trodden path and leave the trailblazing to others.You can profit by their mistakes and wisely make the necessary corrections as you go along.\n",

    "Disharmony and unpleasant situations disturb you greatly, and therefore you go out of your way to keep peace and calm troubled waters.Your Concern and consideration for others bring you a host of friends whom you appreciate and treasure.Two outstanding traits that count heavily toward the attainment of anything you desire are your diplomacy and tact.You can do things so gracefully that there never is much of a problem in getting your own way.\n",

    "You are most successful when completing the plans or executing the directives of others who are less capable of handling the organization and detail.It is best not to attempt to originate ideas or businesses on your own.\n",

    "you have an unusual spirit of independence that makes you the perfect helpmate, yet completely self-sufficient if you need to be.You can easily and most satisfactorily take over the business responsibilities when left in charge, or those of the household when your mate is elsewhere.\n",

    "It will your nature to forgive and understand easily, which, again, makes you the perfect mate.Should there be trouble within your marriage, chances are that you would be the one to make sacrifices or compromises in order to overcome it.The great powers you have been endowed with allow you to forgive any transgression on the part of your mate, but you must take care to avoid being so forgiving that transgressions become a habit on their part.\n",

    "In your effort to please, you can too easily be influenced against your better judgment.You can also be moody and undecided, not to mention oversensitive.There are times when your uncertainty allows others to get the best of you, and this could make you resentful.\n",
];


module.exports.fortune = fortune;
